# Generated by Django 2.2.19 on 2022-01-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте картинку', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
